import type { Locale } from "@/lib/i18n/translations";

const LABELS: Record<Locale, Record<string, string>> = {
  "pt-BR": {
    new: "Novo",
    reviewed: "Revisado",
    approved: "Aprovado",
    contacted: "Contatado",
    replied: "Respondeu",
    interested: "Interessado",
    closed: "Fechado",
    not_interested: "Sem interesse",
    do_not_contact: "Não contatar",
    google_places: "Google Places",
    website: "Site",
    manual_import: "Importação manual",
    demo_seed: "Demo",
    merged: "Mesclado",
    ideal_sme: "PME ideal",
    possible_sme: "PME possível",
    large_enterprise: "Grande empresa",
    unknown: "Não classificado",
    matched: "Confirmado",
    needs_review: "Precisa revisão",
    not_found: "Sem correspondência",
    error: "Erro",
    varejo: "Varejo",
    atacado: "Atacado",
    distribuidora: "Distribuidora",
    ecommerce: "E-commerce",
    industria: "Indústria",
    construcao_civil: "Construção civil",
    enriched: "Enriquecimento",
    assigned: "Atribuição",
    imported: "Importação",
    created: "Criação",
    blocked: "Bloqueio",
    unblocked: "Desbloqueio",
    updated: "Atualização",
    email: "Email",
    whatsapp: "WhatsApp",
    instagram: "Instagram",
    phone: "Telefone",
    contact_form: "Formulário",
    contact_page: "Página de contato",
    homepage: "Página inicial",
    about_page: "Página institucional",
    page: "Página",
  },
  en: {
    new: "New",
    reviewed: "Reviewed",
    approved: "Approved",
    contacted: "Contacted",
    replied: "Replied",
    interested: "Interested",
    closed: "Closed",
    not_interested: "Not interested",
    do_not_contact: "Do not contact",
    google_places: "Google Places",
    website: "Website",
    manual_import: "Manual import",
    demo_seed: "Demo",
    merged: "Merged",
    ideal_sme: "Ideal SME",
    possible_sme: "Possible SME",
    large_enterprise: "Large enterprise",
    unknown: "Unclassified",
    matched: "Confirmed",
    needs_review: "Needs review",
    not_found: "No match",
    error: "Error",
    varejo: "Retail",
    atacado: "Wholesale",
    distribuidora: "Distributor",
    ecommerce: "E-commerce",
    industria: "Industry",
    construcao_civil: "Construction",
    enriched: "Enrichment",
    assigned: "Assignment",
    imported: "Import",
    created: "Creation",
    blocked: "Block",
    unblocked: "Unblock",
    updated: "Update",
    email: "Email",
    whatsapp: "WhatsApp",
    instagram: "Instagram",
    phone: "Phone",
    contact_form: "Form",
    contact_page: "Contact page",
    homepage: "Homepage",
    about_page: "About page",
    page: "Page",
  },
};

export function formatLeadLabel(value?: string | null, locale: Locale = "pt-BR") {
  if (!value) {
    return null;
  }
  return LABELS[locale][value] ?? value.replace(/_/g, " ").replace(/\b\w/g, (character) => character.toUpperCase());
}
